### ISSUE TITLE
inward lab test request

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#208]
need to be added to lab test from path lab.
need a privilege to add service in inward.

![lab privilege](https://cloud.githubusercontent.com/assets/7201585/5522594/3155ddc2-89e1-11e4-94e2-2f2b8114c9b0.png)

**Comment by HNDITDushan** [comment]
Don't Give access to inward menu to lab members

![issue 208](https://cloud.githubusercontent.com/assets/3907163/10273248/ff64b79c-6b4a-11e5-8128-c1e889739973.JPG)
