### ISSUE TITLE
Display Leave Creater

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#228]
http://192.168.122.88:8080/ruhunu1/faces/hr/hr_report_leave_summery_by_staff.xhtml

**Comment by piumini** [comment]
Also Leave deductions are NOT displayed.

**Comment by buddhika75** [comment]
Leave Creator is now displayed. Please create a new issue for not displaying Leave Deductions. CLose this issue if creator is displayed. Use one issue for one problem.
