### ISSUE TITLE
 pharmacy transfer issue

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#237]
when opening for issuing for transfer request , when browser is close or sign out issuing cannot be done for that request.even the stock is redused from those items.

**Comment by HNDITDushan** [comment]
i check that but there has no any kind of issue. Plz check again.

**Comment by buddhika75** [comment]
I tried to replicate issue, but could not reproduce. Please call me and demonstrate. For the error that has occurred previously, the bill was stopped halfway and and not find a reason. Need to check the way that particular end user do it.
