### ISSUE TITLE
report/ month end daily retun 

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#243]
![month end](https://cloud.githubusercontent.com/assets/7201585/7742675/914af8c2-ffaf-11e4-89a5-fc833b1372a0.png)

can't get break down for immunization category total. using this path .. Reports -> institution reports ->Summary By Service Opd -> summery by service category

**Comment by HNDITDushan** [comment]
plz do that.
1.get the "Immunization" category service items.
2.change category "Immunization" to "Immunization Immunization"
3.then check that report
