### ISSUE TITLE
general stores / unit isse

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#244]
![gen](https://cloud.githubusercontent.com/assets/7201585/7742856/068bdb5e-ffb2-11e4-9ce4-d5509daf278c.png)

**Comment by buddhika75** [comment]
Done. please pull for latest changes and close.
![issue-244-after](https://cloud.githubusercontent.com/assets/1226946/7763673/356bd18a-0062-11e5-944b-4d985bbd68d9.png)
![issue-244-before](https://cloud.githubusercontent.com/assets/1226946/7763674/356f756a-0062-11e5-8f74-b3a79359f481.png)
