### ISSUE TITLE
INWARD/ time service

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#256]
#220
after adding a time service into the bill, the end time is auto set

**Comment by lahirumadushanka** [comment]
i think i found the issue. after adding time service there is a save button, after clicking that button if todate is null it will set current date.so i removed it and validated todate entry.

**Comment by lahirumadushanka** [comment]
please check and close.

**Comment by lahirumadushanka** [comment]
piumi says that dont auto set time or amount.user want to add it manually.

**Comment by buddhika75** [comment]
Now can add or change & Update timed services without end time.
d21e4f4d5ed7eb3c8043c8a896a58f1c547dfc05

Please check and close
