### ISSUE TITLE
salary process 

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#265]
![salary process](https://cloud.githubusercontent.com/assets/7201585/8107456/e212fa6c-1066-11e5-842e-120b71765f3e.png)

![additional working](https://cloud.githubusercontent.com/assets/7201585/8107482/1b42360e-1067-11e5-95b6-5d439b179cd2.png)

![over time report](https://cloud.githubusercontent.com/assets/7201585/8107516/681b84ee-1067-11e5-9b19-ce586c98f7d8.png)

**Comment by lahirumadushanka** [comment]
first one done.....if "Total PH/Off/Poya/Basic Adjustments" means "PoyaAllowance + DayOffAllowance" as you marked in the picture.

**Comment by lahirumadushanka** [comment]
done..please check and close

**Comment by lahirumadushanka** [comment]
piumi said this is not an issue after i going through this. she said there is no issue in the code this issue opened by her mistake and requested to redo all.
