### ISSUE TITLE
daily return / cancel bill error

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#269]
inward service canceled bill amount reduced from daily return Credit Card Transactions.
daily return date 2015.06.09

![daily](https://cloud.githubusercontent.com/assets/7201585/8228042/6b0b7df0-15c9-11e5-9b74-b6384cce1da0.png)

![inward cancell](https://cloud.githubusercontent.com/assets/7201585/8228040/65ed79b8-15c9-11e5-9712-1bde251b8fa7.png)

**Comment by HNDITDushan** [comment]
done.fech new changes run and contact me
