### ISSUE TITLE
new pharmacy / summery

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#294]
NO PHARMACY BILL SALE  
![697](https://cloud.githubusercontent.com/assets/7201585/9247362/13b40bfc-41d0-11e5-9404-7ca3488ada8e.png)

**Comment by buddhika75** [comment]
What is the issue?

**Comment by HNDITDushan** [comment]
if you want to show the details of pharmacy summery plz check 1)Cashier Detailed
![294](https://cloud.githubusercontent.com/assets/3907163/9267386/c820dd4a-426b-11e5-9050-825c01dea10b.JPG)
