### ISSUE TITLE
channel summery 

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#310]
check channel refund summery  .

![scan0008](https://cloud.githubusercontent.com/assets/7201585/10073323/9fab6a84-62e5-11e5-9c9e-6e731d4052bd.jpg)
![scan0009](https://cloud.githubusercontent.com/assets/7201585/10073324/9fb00d82-62e5-11e5-8ec2-5730ac39e210.jpg)
![scan0010](https://cloud.githubusercontent.com/assets/7201585/10073326/9fb1804a-62e5-11e5-92f7-186bef5f4800.jpg)
![scan0011](https://cloud.githubusercontent.com/assets/7201585/10073325/9fb14f62-62e5-11e5-9bf5-53ece1df800c.jpg)

**Comment by HNDITDushan** [comment]
done plz check and close
