### ISSUE TITLE
opd/

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#324]
reportCashier/report_opd_package.xhtml
reportCashier/report_opd_package_bill.xhtml

![package pn](https://cloud.githubusercontent.com/assets/7201585/10220578/463373ee-6866-11e5-962f-011a3ce39bd8.png)

![package can](https://cloud.githubusercontent.com/assets/7201585/10220751/4cb53aa8-6867-11e5-89ea-652be647c72b.png)

**Comment by HNDITDushan** [comment]
done
