### ISSUE TITLE
reports/institution report

### ISSUE THREAD

**Issue by piumini** [buddhika75/hmis#325]
![service category](https://cloud.githubusercontent.com/assets/7201585/10240991/74c040a8-6900-11e5-8f7b-a1911a55a6fb.png)

**Comment by HNDITDushan** [comment]
Can't do that.because this report Show The bill-items.

**Comment by piumini** [comment]
search item name as   U S S

**Comment by HNDITDushan** [comment]
done.
![asasas](https://cloud.githubusercontent.com/assets/3907163/10571572/1f9ca3d0-765e-11e5-8689-7c64b27b23bd.JPG)
