### ISSUE TITLE
Originating Session Update issue

### ISSUE THREAD

**Issue by lahirumadushanka** [buddhika75/hmis#354]
when updating originating sessions there is no mechanism to update serviceSessions, please attend this issue asap.

**Comment by buddhika75** [comment]
Dear Dushan, please attend to this asap.

On 3 November 2015 at 10:11, Lahiru Madushanka <notifications@github.com>
wrote:

> when updating originating sessions there is no mechanism to update
> serviceSessions, please attend this issue asap.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buddhika75/hmis/issues/354>.
>



-- 
*Dr. M. H. B. Ariyaratne*
MBBS(Ruhuna), MSc(Biomedical Informatics)
Medical Officer (Health Information)

*Official Address*
Department of Health Services - Southern Province,
No 15A, Lower Dickson Road,
Galle, Sri Lanka.

*Residence*
36/A, Thalgahahena Lane,
Galle, Sri Lanka.

Mobile    : + 94 71 5812399
Residence : + 94 91 2241603
Email     : buddhika.ari@gmail.com
Website   : www.lakmedi.com

**Comment by anukadesilva** [comment]
please doctor mawa github eken remove karanna. mata karadarak eka

**Comment by buddhika75** [comment]
Dear Anushka,

We can not remove other users.  You can simply unsubscribe it.

Regards,

On 4 November 2015 at 05:50, anukadesilva <notifications@github.com> wrote:

> please doctor mawa github eken remove karanna. mata karadarak eka
>
>
> On Tue, Nov 3, 2015 at 4:05 AM, Dr. M H B Ariyaratne <
> notifications@github.com> wrote:
>
> > Dear Dushan, please attend to this asap.
> >
> > On 3 November 2015 at 10:11, Lahiru Madushanka <notifications@github.com
> >
> > wrote:
> >
> > > when updating originating sessions there is no mechanism to update
> > > serviceSessions, please attend this issue asap.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/buddhika75/hmis/issues/354>.
> > >
> >
> >
> >
> > --
> > *Dr. M. H. B. Ariyaratne*
> > MBBS(Ruhuna), MSc(Biomedical Informatics)
> > Medical Officer (Health Information)
> >
> > *Official Address*
> > Department of Health Services - Southern Province,
> > No 15A, Lower Dickson Road,
> > Galle, Sri Lanka.
> >
> > *Residence*
> > 36/A, Thalgahahena Lane,
> > Galle, Sri Lanka.
> >
> > Mobile : + 94 71 5812399
> > Residence : + 94 91 2241603
> > Email : buddhika.ari@gmail.com
> > Website : www.lakmedi.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/buddhika75/hmis/issues/354#issuecomment-153253374>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buddhika75/hmis/issues/354#issuecomment-153531920>.
>



-- 
*Dr. M. H. B. Ariyaratne*
MBBS(Ruhuna), MSc(Biomedical Informatics)
Medical Officer (Health Information)

*Official Address*
Department of Health Services - Southern Province,
No 15A, Lower Dickson Road,
Galle, Sri Lanka.

*Residence*
36/A, Thalgahahena Lane,
Galle, Sri Lanka.

Mobile    : + 94 71 5812399
Residence : + 94 91 2241603
Email     : buddhika.ari@gmail.com
Website   : www.lakmedi.com

**Comment by HNDITDushan** [comment]
done.
